#!/bin/zsh

# # laod env
source ~/.zshrc

savvy(){
echo """
# -*- coding: utf-8 -*-

import os, sys, time
from datetime import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pprint import pprint as show
from evolving.evolving import Service, Evolving, EvolvingSim
from evolving.helper import Msg, Mail, Logging, Tlog
s = Service()
e = Evolving()
es = EvolvingSim()
e.keepInformed = True

hints = '''
# os, sys, time, datetime, np, pd, plt, show, Service, Evolving, EvolvingSim, Msg, Mail, Logging were imported
# s = Service()
# e = Evolving()
# es = EvolvingSim()
# e.keepInformed = True
'''

print('Evo !')
print('-------------------------')
print(hints)
""" > ~/.ipython/profile_default/startup/startup.py

ipython --no-banner --quiet --no-confirm-exit
}

helpfun(){
	doc='
	NAME:
		evo
	SYNOPSIS:
		evo -[sh]
	OPTIONS:
		-s  shell
		-h  help
	AUTHOR:
		Lorenzo
		Email: zetatez@icloud.com
    Ex:
		1. To use evo shell
			evo -s
	'
	echo ${doc}
}

# parsing args
while getopts :sh opt
do
	case "$opt" in
		s) issavvy="true";;
		h) help="true";;
		*) echo "unknown option: $opt, try evo -h";;
	esac
done

if [ ${help} ]; then
	helpfun
fi

if [ ${issavvy} ]; then
    savvy
fi

