#!/bin/zsh

# laod env
source ~/.zshrc

# configure
curMonth=`date +%Y-%m`
modelPath=$(cd `(dirname $0)`; cd ..; pwd)
logPath=${modelPath}/evolving/logs/terminal/${curMonth}.log

# functions
logger(){
    echo `date +%F\ %T`: "${1}" >> ${logPath}
    echo `date +%T`: "${1}"
}

loginClient(){
	nohup osascript ${modelPath}/evolving/swap/loginClient.scpt ${1} ${2} >> /dev/null 2>&1 &
	logger "login  client . .. ..."
}

logoutClient(){
	nohup osascript ${modelPath}/evolving/swap/logoutClient.scpt >> /dev/null 2>&1 &
	logger "logout client . .. ..."
}

savvy(){
	# start ipython
	# load useful modules on start up
	logger "savvy . .. ..."
	cp ${modelPath}/evolving/.darwinshellstartup.py ~/.ipython/profile_default/startup/startup.py 
	ipython --no-confirm-exit
}

helpfun(){
	doc='
	NAME:
		darwin

	SYNOPSIS:
		darwin -u userid -p password
		darwin -u userid -p password -k
		darwin -[qsjh]

	OPTIONS:
		-u  userid
		-p  password
		-q  quit client
		-s  start darwin shell
		-h  help

	AUTHOR:
		F. F
		Email: fromfairest@icloud.com

	Ex:
		1. To login client
			darwin -u userid -p password

		2. To logout client
			darwin -q

		3. To use darwin shell
			darwin -s

		4. login client, start darwin shell
			darwin -u userid -p password -s
	'
	echo ${doc}
}

# parsing arguments
while getopts :u:p:qskjh opt
do
	case "$opt" in
		u) userid=$OPTARG;;
		p) password=$OPTARG;; 			# login client by default
		q) logout="true";;				# logout client
		s) darwinShell="true";;			# enter darwin shell
		h) help="true";;
		*) echo "unknown option: $opt" ;;
	esac
done

if [ ${help} ]; then
	helpfun
fi

if [ ${userid} ] && [ ${password} ]; then
	if [ ${up} ]; then
		upDaemonService ${userid} ${password}
	else
		loginClient ${userid} ${password}
	fi
fi

if [ ${logout} ]; then
	logoutClient
fi

if [ $darwinShell ]; then
	savvy
fi
